export type SampleCatalogEntryData = {
  name: string;
  unit: string;
  category?: string;
};

export const sampleCatalogEntries: SampleCatalogEntryData[] = [
  { name: "Kabel 3x1.5mm2", unit: "m" },
  { name: "CAT7 Datenkabel", unit: "m" },
  { name: "CAT7 Stecker", unit: "stk" },
  { name: "Kabel 5x1.5mm2", unit: "m" },
  { name: "Kabel 5x2.5mm2", unit: "m" },
  { name: "Kabel 5x4mm2", unit: "m" },
  { name: "Kabel 5x6mm2", unit: "m" },
  { name: "Kabel 7x1,5mm2", unit: "m" },
  { name: "Kabel 3x1mm2", unit: "m" },
  { name: "Kabel 2x1mm2", unit: "m" },
  { name: "PV Kabel 6mm2", unit: "m" },
  { name: "PV Stecker", unit: "pkg" },
  { name: "C16 2pol", unit: "stk" },
  { name: "C16 3pol", unit: "stk" },
  { name: "C16 4pol", unit: "stk" },
  { name: "C13 2pol", unit: "stk" },
  { name: "N Durchfuehrung", unit: "stk" },
  { name: "CAT7 Duplex", unit: "m" },
  { name: "Erdung 16mm2", unit: "m" },
  { name: "Erdungswuerfel", unit: "stk" },
  { name: "FI 40A 30mA", unit: "stk" },
  { name: "Hauptleiterklemme isoliert 4pol", unit: "stk" },
  { name: "Julie 150", unit: "stk" },
  { name: "Kabel 1x10mm2", unit: "m" },
  { name: "Klemmdose TK40", unit: "stk" },
  { name: "Rohr 20mm", unit: "stk" },
  { name: "Rohr 25mm", unit: "stk" },
  { name: "Rohr 32mm", unit: "stk" },
  { name: "Rohr 40mm", unit: "stk" },
  { name: "Schelle 20mm", unit: "stk" },
  { name: "Schelle 25mm", unit: "stk" },
  { name: "Schelle 32mm", unit: "stk" },
  { name: "Schelle 40mm", unit: "stk" },
  { name: "Schlauch 20mm", unit: "m" },
  { name: "Schlauch 25mm", unit: "m" },
  { name: "Schlauch 32mm", unit: "m" },
  { name: "Schlauch 40mm", unit: "m" },
  { name: "Verschienung", unit: "m" },
  { name: "Verschienung Abdeckung", unit: "m" },
  { name: "Verschienung Endkappen", unit: "stk" },
  { name: "Verschienung Anschlusswinkel", unit: "stk" },
  { name: "Ueberspannungsbox 2fach", unit: "stk" },
  { name: "Ueberspannungsbox 1fach", unit: "stk" },
  { name: "AP Schalter", unit: "stk" },
  { name: "AP Schalter+Steckdose", unit: "stk" },
  { name: "AP Steckdose 1-fach", unit: "stk" },
  { name: "AP Steckdose 2-fach", unit: "stk" },
  { name: "AP Verteiler 1-reihig", unit: "stk" },
  { name: "AP Verteiler 2-reihig", unit: "stk" },
  { name: "AP Verteiler 3-reihig", unit: "stk" },
  { name: "AP Verteiler 4-reihig", unit: "stk" },
  { name: "AP CEE 16A + Steckdose", unit: "stk" },
  { name: "AP CEE 16A", unit: "stk" },
];
